export const GAME = {
  CANVAS_WIDTH: 480,
  CANVAS_HEIGHT: 720,
  PLAYER_SPEED: 5,
  BULLET_SPEED: 8,
  ENEMY_SPEED: 2,
  PLAYER_SIZE: 20,
  BULLET_WIDTH: 4,
  BULLET_HEIGHT: 12,
  ENEMY_SIZE: 24,
  MAX_LIVES: 3,
  ENEMY_SCORE: 100,
  FIRE_RATE: 150,
};

